/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xzy_myjnitest_JNIMethod */

#ifndef _Included_com_xzy_myjnitest_JNIMethod
#define _Included_com_xzy_myjnitest_JNIMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xzy_myjnitest_JNIMethod
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xzy_myjnitest_JNIMethod_hello
  (JNIEnv *, jclass);

/*
 * Class:     com_xzy_myjnitest_JNIMethod
 * Method:    avcoder_find_decoder
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xzy_myjnitest_JNIMethod_avcoder_1find_1decoder
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_xzy_myjnitest_JNIMethod
 * Method:    run
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xzy_myjnitest_JNIMethod_run
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
